title: Asterios Thomas
logo: /assets/img/fotor-2025032014116.png
description: PERSONAL DETAILS
Name: ASTERIOS
Surname: THOMAS
Date of birth: 04/11/2005
Place of birth: THESSALONIKI
Address: LITI-ORIOKASTRO
Phone: 2394073316 Mobile: 6972856393
Email: asteros.thomas@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
