title: Asterios Thomas
logo: /assets/img/fotor-2025032014116.png
description: Asterios Thomas <br>Date of Birth: 04/11/2005 Liti-Thessaloniki 6972856393 asteros.thomas@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
