title: Asterios Thomas
logo: /assets/img/fotor-2025032014116.png
description: <h3>Asterios Thomas <br>04/11/2005 <br>Thessaloniki <br>6972856393 <br>asteros.thomas@gmail.com</h3>

show_downloads: true
theme: jekyll-theme-minimal
