title: Asterios Thomas
logo: /assets/img/fotor-2025032014116.png
description: PERSONAL DETAILS PERSONAL DETAILS ASTERIOSTHOMAS 04/11/2005 THESSALONIKILITI-ORIOKASTROasteros.thomas@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
