title: Asterios Thomas
logo: /assets/img/fotor-2025032014116.png
description: Asterios Thomas 04/11/2005 Thessaloniki 6972856393 asteros.thomas@gmail.com

show_downloads: true
theme: jekyll-theme-minimal
